-- MCQ V3 Supabase schema.
-- Mirrors db.py's SQLite schema using Postgres-native types.
-- Run this in the Supabase SQL Editor (or apply via psql/pooler).
-- RLS is enabled on every table; the app currently uses the service-role
-- key (trusted server process), which bypasses RLS policies.

create table if not exists public.users (
  id       bigint generated by default as identity primary key,
  email    text not null,
  name     text not null,
  role     text not null check (role in ('teacher', 'student', 'unassigned')),
  password text not null default '',
  constraint users_email_key unique (email)
);

create table if not exists public.admins (
  id         bigint generated by default as identity primary key,
  email      text not null unique,
  password   text not null,
  name       text not null,
  created_at timestamptz not null
);

create table if not exists public.quizzes (
  id                 bigint generated by default as identity primary key,
  owner_id           bigint not null references public.users (id),
  title              text not null,
  duration_minutes   integer not null,
  passing_score      integer not null,
  quiz_length        integer,
  allow_retake       integer not null default 0,
  show_average       integer not null default 0,
  opening_time       timestamptz not null,
  closing_time       timestamptz not null,
  opening_enabled    integer not null default 1,
  closing_enabled    integer not null default 1,
  randomize_questions integer not null default 1,
  randomize_answers  integer not null default 1,
  status             text not null default 'active',
  created_at         timestamptz not null
);

create table if not exists public.quiz_students (
  quiz_id     bigint not null references public.quizzes (id) on delete cascade,
  student_id  bigint not null references public.users (id) on delete cascade,
  assigned_at timestamptz not null,
  primary key (quiz_id, student_id)
);

create table if not exists public.teacher_students (
  teacher_id bigint not null references public.users (id) on delete cascade,
  student_id bigint not null references public.users (id) on delete cascade,
  added_at   timestamptz not null,
  primary key (teacher_id, student_id)
);

create table if not exists public.teams (
  id         bigint generated by default as identity primary key,
  teacher_id bigint not null references public.users (id) on delete cascade,
  name       text not null,
  created_at timestamptz not null,
  constraint teams_teacher_id_name_key unique (teacher_id, name)
);

create table if not exists public.team_students (
  team_id    bigint not null references public.teams (id) on delete cascade,
  student_id bigint not null references public.users (id) on delete cascade,
  added_at   timestamptz not null,
  primary key (team_id, student_id)
);

create table if not exists public.questions (
  id            bigint generated by default as identity primary key,
  quiz_id       bigint not null references public.quizzes (id) on delete cascade,
  question_text text not null,
  options_json  text not null,
  correct_label text not null,
  question_type text not null default 'Multiple choice',
  position      integer not null
);

create table if not exists public.attempts (
  id             bigint generated by default as identity primary key,
  quiz_id        bigint not null references public.quizzes (id) on delete cascade,
  student_id     bigint not null references public.users (id),
  started_at     timestamptz not null,
  deadline_at    timestamptz not null,
  submitted_at   timestamptz,
  score_percent  double precision,
  passed         integer,
  auto_submitted integer not null default 0,
  answers_json   text not null default '{}'
);

create unique index if not exists one_open_attempt
  on public.attempts (quiz_id, student_id) where submitted_at is null;

create index if not exists quizzes_owner_idx on public.quizzes (owner_id);
create index if not exists questions_quiz_idx on public.questions (quiz_id, position);
create index if not exists attempts_quiz_idx on public.attempts (quiz_id);
create index if not exists attempts_student_idx on public.attempts (student_id);
create index if not exists quiz_students_student_idx on public.quiz_students (student_id);
create index if not exists teacher_students_student_idx on public.teacher_students (student_id);

alter table public.users enable row level security;
alter table public.admins enable row level security;
alter table public.quizzes enable row level security;
alter table public.quiz_students enable row level security;
alter table public.teacher_students enable row level security;
alter table public.teams enable row level security;
alter table public.team_students enable row level security;
alter table public.questions enable row level security;
alter table public.attempts enable row level security;

-- Table-level privileges (the "automatically expose new tables" option is
-- disabled, so grants must be explicit). The app uses the service-role key;
-- anon/authenticated grants are kept minimal for future RLS policies.
grant usage on schema public to anon, authenticated, service_role;
grant all on all tables in schema public to anon, authenticated, service_role;
grant all on all sequences in schema public to anon, authenticated, service_role;
grant all on all functions in schema public to anon, authenticated, service_role;

-- Google sign-in onboarding: new accounts start 'unassigned' until an admin
-- assigns them a role. Relax the users.role constraint (idempotent).
alter table public.users drop constraint if exists users_role_check;
alter table public.users add constraint users_role_check
  check (role in ('teacher', 'student', 'unassigned'));

-- Re-align identity sequences after a backfill that inserted explicit ids
-- (identity columns don't auto-advance on explicit inserts). Idempotent.
select setval(pg_get_serial_sequence('public.users', 'id'), coalesce((select max(id) from public.users), 1));
select setval(pg_get_serial_sequence('public.admins', 'id'), coalesce((select max(id) from public.admins), 1));
select setval(pg_get_serial_sequence('public.quizzes', 'id'), coalesce((select max(id) from public.quizzes), 1));
select setval(pg_get_serial_sequence('public.questions', 'id'), coalesce((select max(id) from public.questions), 1));
select setval(pg_get_serial_sequence('public.attempts', 'id'), coalesce((select max(id) from public.attempts), 1));
select setval(pg_get_serial_sequence('public.teams', 'id'), coalesce((select max(id) from public.teams), 1));